---
platform: linux
image: ff-docker-image
inputs:
  - name: git-repo
outputs:
  - name: validation
params:
run:
  path: bash
  args:
    - -c
    - |
     set -e
     cd git-repo
     bundle install
