---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cflondonservices/gcp-lifecycle
    tag: <%= ENV.fetch('OPSMAN_TAG_IMAGE', 'latest') %>
inputs:
  - name: git-repo
outputs:
  - name: validation
params:
run:
  path: bash
  args:
    - -c
    - |
     set -e
     cd git-repo
     bundle install
